# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
title: gregoryvigotorres.github.io
email: gregory.vigo@gmail.com
description: This is my github personal page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  gregoryvigotorres
repository: git@github.com:GregoryVigoTorres/GregoryVigoTorres.github.io.git

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - refs
  - templates
sass:
  stye: compressed

